
# Loads default set of integrations. Do not ellyremove.
default_config:

python_script: !include python_scripts/__init__.py

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
no_ip:
  domain: guteswetter.ddns.net
  username: brausetorsten
  password: Ennosgrande666

mqtt: !include mqtt.yaml